name: lks-dev-pipeline

on:
  push:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Check Docker Version
  run: docker --version


      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          region: us-east-1

      - name: Login to ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 629860297780.dkr.ecr.us-east-1.amazonaws.com

      - name: Build & Push vote image
        run: |
          docker build -t vote ./vote
          docker tag vote:latest 629860297780.dkr.ecr.us-east-1.amazonaws.com/lks-voting-image:vote-dev-latest
          docker push 629860297780.dkr.ecr.us-east-1.amazonaws.com/lks-voting-image:vote-dev-latest

      - name: Build & Push result image
        run: |
          docker build -t result ./result
          docker tag result:latest 629860297780.dkr.ecr.us-east-1.amazonaws.com/lks-voting-image:result-dev-latest
          docker push 629860297780.dkr.ecr.us-east-1.amazonaws.com/lks-voting-image:result-dev-latest

      - name: Build & Push worker image
        run: |
          docker build -t worker ./worker
          docker tag worker:latest 629860297780.dkr.ecr.us-east-1.amazonaws.com/lks-voting-image:worker-dev-latest
          docker push 629860297780.dkr.ecr.us-east-1.amazonaws.com/lks-voting-image:worker-dev-latest

  pull-master:
    runs-on: [self-hosted, master]
    needs: build
    steps:
      - name: Pull images
        run: |
          docker pull 629860297780.dkr.ecr.us-east-1.amazonaws.com/lks-voting-image:vote-dev-latest
          docker pull 629860297780.dkr.ecr.us-east-1.amazonaws.com/lks-voting-image:result-dev-latest
          docker pull 629860297780.dkr.ecr.us-east-1.amazonaws.com/lks-voting-image:worker-dev-latest

  pull-node1:
    runs-on: [self-hosted, node1]
    needs: build
    steps:
      - name: Pull images
        run: |
          docker pull 629860297780.dkr.ecr.us-east-1.amazonaws.com/lks-voting-image:vote-dev-latest
          docker pull 629860297780.dkr.ecr.us-east-1.amazonaws.com/lks-voting-image:result-dev-latest
          docker pull 629860297780.dkr.ecr.us-east-1.amazonaws.com/lks-voting-image:worker-dev-latest

  pull-node2:
    runs-on: [self-hosted, node2]
    needs: build
    steps:
      - name: Pull images
        run: |
          docker pull 629860297780.dkr.ecr.us-east-1.amazonaws.com/lks-voting-image:vote-dev-latest
          docker pull 629860297780.dkr.ecr.us-east-1.amazonaws.com/lks-voting-image:result-dev-latest
          docker pull 629860297780.dkr.ecr.us-east-1.amazonaws.com/lks-voting-image:worker-dev-latest

  deploy:
    runs-on: [self-hosted, master]
    needs: [pull-master, pull-node1, pull-node2]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Deploy to Docker Swarm
        run: |
          docker stack deploy -c docker-compose.yml voting

